### ISSUE TITLE
Updating to Travelers 0.3.2 causes crashes with CK3 1.11.2 for some players

### ISSUE THREAD

**Issue by KengelNeh** [pharaox/travelers#1] opened 2023-12-04 20:53 UTC
Latest crushdumps with Travelers mod.
[ck3_20231204_191759.zip](https://github.com/pharaox/travelers/files/13551203/ck3_20231204_191759.zip)

**Comment by KengelNeh** [comment] 2023-12-04 20:56
[ck3_20231204_192232.zip](https://github.com/pharaox/travelers/files/13551241/ck3_20231204_192232.zip)

**Comment by pharaox** [comment] 2023-12-04 21:57
Thanks! Unfortunately, this game was heavily modded, I see a lot of strange errors pointing to missing vanilla events, etc., most likely caused by other mods. Could you please test just with CK3 and Travelers, no other mods (all DLCs enabled), and attach that crash dump? Attaching Travelers 0.3.2 here since Steam should stay on 0.3.1 for the time being.

[travelers-0.3.2.zip](https://github.com/pharaox/travelers/files/13551845/travelers-0.3.2.zip)

**Comment by Uzhirian** [comment] 2023-12-05 00:15
Crashdump with only official DLC and Travelers enabled, though other mods were enable before and are present in the logs (im running about 22 in total + official)
[ck3_20231204_182830_Copy.zip](https://github.com/pharaox/travelers/files/13553155/ck3_20231204_182830_Copy.zip)

**Comment by Uzhirian** [comment] 2023-12-05 00:30
[ck3_20231204_183853_Copy.zip](https://github.com/pharaox/travelers/files/13553427/ck3_20231204_183853_Copy.zip)
Another one if it may help

**Comment by Uzhirian** [comment] 2023-12-05 04:10
@pharaox Alright, new info for you as I've progressed my new hobby of launching CK3.

As per our testing earlier today, after removing Travelers via workshop and manually installing 0.3.2, the game launched OK (running base game + official DLC + Travelers). However, fun fact, when I enabled the other mods in the playset again and launched the game... it crashed.
[ck3_20231205_131012_Copy.zip](https://github.com/pharaox/travelers/files/13554988/ck3_20231205_131012_Copy.zip)

So I disabled all the other mods again, returning to running base game + official DLC + Travelers... and crash.
[ck3_20231205_131431_Copy.zip](https://github.com/pharaox/travelers/files/13554993/ck3_20231205_131431_Copy.zip)

I turned off Travelers and enabled all the other mods again... and all good, no crash.

Then I turned off all mods, launched the game and no crashes (that would be awkward if it had crashed here haha)

I re-enable Travelers only again, launched game... and no crash this time.
I repeated this again to see what happened... and crash... and no crash... and crash... and crash... and no crash. 
[ck3_20231205_143256_Copy.zip](https://github.com/pharaox/travelers/files/13554994/ck3_20231205_143256_Copy.zip)
[ck3_20231205_143912_Copy.zip](https://github.com/pharaox/travelers/files/13554995/ck3_20231205_143912_Copy.zip)
[ck3_20231205_144158_Copy.zip](https://github.com/pharaox/travelers/files/13554996/ck3_20231205_144158_Copy.zip)

Seems it's not as consistently crashing as I first thought (I didn't run enough test iterations before I guess but in my defence CK3 takes a while to load and I'm lazy and it was like 4am in the morning). It is definitely crashing much more than not though with Travelers 0.3.2 enabled and I haven't experienced any crashes at all with the old travelers version or no travelers mod enabled (and early in my current play-through a couple of days ago I was launching the game quite a lot to test different skin texture/beauty trait altering mods).

I haven't loaded a save/started any new games during any of these tests so the 'last_save.ck3' should be unchanged (it was too large to upload here so I removed that file from all the zips). Only difference between tests are mod changes and/or whatever files are altered by the game during launch.

**Comment by pharaox** [comment] 2023-12-05 22:47
@Uzhirian Many thanks for your tests and the info! I was finally able to reproduce the crash, it was pretty consistent on Windows if subscribed via Steam with Travelers only. This commit 5f11b357699baacbd5ea1d2b7f9ba45cf2619280 should solve it (it basically moves some localization files to a different folder). I develop and test on Linux, and only managed to get to a Windows machine today for testing. 

The new version is on Steam, could you please check and confirm if the crashes are gone with it? Just use it together with all your mods, and if it still crashes, unsubscribe and resubscribe on Steam and try again. Make sure to delete the local one from your mod folder.

**Comment by pharaox** [comment] 2023-12-16 11:40
Fixed in version 0.3.3 by reverting the offending commit (2a5f3d79ebf6c65167219aadb3263a353981db01), the same functionality was reintroduced without issues in 0.3.4 (4a557fe9c57556ed5159ec6cc5ca2e455a77ac9e).

**Closed as completed by pharaox** 2023-12-16 11:40 UTC
